version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Instalando dependencias y versiones..."

  pre_build:
    commands:
      - echo "Restaurando paquetes .NET..."
      - dotnet restore productCRUD/productCRUD.csproj

  build:
    commands:
      - echo "Compilando la solución .NET..."
      - dotnet build productCRUD/productCRUD.csproj --configuration Release --no-restore

  post_build:
    commands:
      - echo "Publicando la aplicación .NET..."
      - dotnet publish productCRUD/productCRUD.csproj --configuration Release --no-build --output productCRUD/published
      - echo "Listando archivos en la carpeta published..."
      - ls -R productCRUD/published

artifacts:
  files:
    - productCRUD/published/**/*
  discard-paths: no
