version: 0.2

phases:
  install:
    # Indica la versi칩n de .NET que necesitas (puede ser 6.0, 7.0, 8.0, etc.)
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Instalando dependencias y versiones..."

  pre_build:
    commands:
      - echo "Restaurando paquetes .NET..."
      # Ajusta la ruta de tu .csproj si est치 en otro lugar
      - dotnet restore productCRUD/productCRUD.csproj

  build:
    commands:
      - echo "Compilando la soluci칩n .NET..."
      - dotnet build productCRUD/productCRUD.csproj --configuration Release --no-restore

  post_build:
    commands:
      # (Opcional) ejecutar pruebas, si tienes un proyecto de test separado:
      # - dotnet test productCRUD.Tests/productCRUD.Tests.csproj --no-build

      - echo "Publicando la aplicaci칩n .NET..."
      - dotnet publish productCRUD/productCRUD.csproj --configuration Release --no-build --output productCRUD/published

artifacts:
  # Exporta todo el contenido de la carpeta "published"
  files:
    - productCRUD/published/**/* 
  discard-paths: no

